name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  DEV_DATABASE_PASSWORD: ${{ secrets.DEV_DATABASE_PASSWORD }}
  DEV_DATABASE_USERNAME: ${{ secrets.DEV_DATABASE_USERNAME }}
  ENCRYPTION_SALT: ${{ secrets.ENCRYPTION_SALT }}
  ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
  GOOGLE_STATIC_MAPS_API_KEY: ${{ secrets.GOOGLE_STATIC_MAPS_API_KEY }}
  GOOGLE_STATIC_MAPS_SIGNING_SECRET: ${{ secrets.GOOGLE_STATIC_MAPS_SIGNING_SECRET }}
  HTTP_API_KEY: ${{ secrets.HTTP_API_KEY }}
  DEV_JDBC_URL: ${{ secrets.DEV_JDBC_URL }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENDGRID_EVENT_CANCELLED_TEMPLATE_ID: ${{ secrets.SENDGRID_EVENT_CANCELLED_TEMPLATE_ID }}
  SENDGRID_EVENT_CONFIRMATION_TEMPLATE_ID: ${{ secrets.SENDGRID_EVENT_CONFIRMATION_TEMPLATE_ID }}
  SENDGRID_EVENT_INVITE_TEMPLATE_ID: ${{ secrets.SENDGRID_EVENT_INVITE_TEMPLATE_ID }}
  SENDGRID_EVENT_RESCHEDULED_TEMPLATE_ID: ${{ secrets.SENDGRID_EVENT_RESCHEDULED_TEMPLATE_ID }}
  SENDGRID_INVITE_RESPONSE_TEMPLATE_ID: ${{ secrets.SENDGRID_INVITE_RESPONSE_TEMPLATE_ID }}
  SENDGRID_MAGIC_LINK_TEMPLATE_ID: ${{ secrets.SENDGRID_MAGIC_LINK_TEMPLATE_ID }}
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: groupevent
          POSTGRES_USER: ${{ env.DEV_DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.DEV_DATABASE_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.1.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: corretto
      - name: Maven Build
        run: |
          ./mvnw --no-transfer-progress clean package